name: deploy to github pages

on: [pull_request]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup npm
        run: yarn install --frozen-lockfile

      - name: Build
        env: 
          SKYWAY_API_KEY: ${{secrets.SKYWAY_API_KEY}}
        run: SKYWAY_API_KEY=${{secrets.SKYWAY_API_KEY}} yarn run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist